PATHO_LABELS = {
  "DEMO":{
    "description":
        "DEMO",
    "vocabulary": ["pathogen", "virulen", "infet"],
    "abbreviation":["UPEC"]
  },
  "DEMO_nonpatho":{
    "description":
        "DEMO",
    "vocabulary": ["nonpathogen", "microbiom"],
    "abbreviation":["HMP"]
  },
  "Pathogen":{
    "description":
        "Vocabulary that any pathogen detection metadata could contain",
    "vocabulary":["infet", "virulen", "pathogen", "infec", "incfect", "infenct",
        "superbug", "patholog"],
    "abbreviation":[]
    },
  "Possible Pathogen":{
    "description":
        "Vocabulary that can be only related to pathogens",
    "vocabulary":["fatal", "borne", "epidemi", "damag", "toxic", "coloni",
        "outbreak", "invasiv", "endemi", "contamina", "transmit", "poison",
        "prolifera", "opportunisti", "toxi"],
    "abbreviation":[]
    },
  "Disease Caused By Pathogen":{
    "description":
        "Name of diseases only caused by bacteria pathogens",
    "vocabulary":["necrotis", "reiter", "pneumoni", "bacterremi",
        "meningococcemi", "bacteremi", "tubersulosi", "pnneumoni",
        "shigellosi", "botulism", "suppurativ", "borreliosi", "osteomyeliti",
        "meningococcal", "bacteriaemi", "yaws", "tubercolusi",
        "buruli", "mycobacteriosis", "vibriosis", "rickettsiosis", "scarlatina",
        "paratyphoid", "campylobacteriosis", "anthrax", "speticemia",
        "uropathogeni", "diphtheri", "leprosy", "pneumorni", "pyomyositis",
        "nocardiosis", "enterobrosis", "enterobiasis", "settico",
        "Legionnaire", "bacteraemi", "erysipeloid", "typhoid", "listerios",
        "septicimi", "bacteriuri", "enterohemorrhagi", "septicaemi", "nephriti",
        "spetic", "gastroenterit", "peritoniti", "diphteri", "anaplasmosi",
        "herpe", "septecemia", "hcap", "cdi", "enterocolitis",
        "cholera", "gingivitis", "trachoma", "syphilis", "lgv", "melliodosis",
        "legionellosis", "listerosi", "gonococcal", "meningitidi", "chlamydia",
        "enteriti", "pertussis", "brucellios", "tonsilliti", "meningitis",
        "necroticans", "pneamonia", "endometritisis", "trachitis",
        "bacterimea","septicopyemia", "mycetoma", "plague", "phlegmonous",
        "dysentery", "gonorrhea", "pleumonia", "erysipelas", "septicemic",
        "pertussin", "bactremia", "impetigo", "spondylodiscitis",
        "actinomycosis", "legionnaire", "yersiniosis", "necrotiz",
        "nosocomical", "bacteriemia", "endocarditis", "tetanus",
        "discitis", "septoc", "whooping", "pnemonia", "bubonic", "cruris",
        "salmonelosis", "tonsillopharyngitis", "meliodosis", "sepsis",
        "omphalitis", "bacteremia", "sepcis", "pneumonia", "lemierre",
        "penumonia", "enterrohemorragic", "leptospirosis",  "tonsilitis",
        "candidiasis", "tuberculosis", "candidemia", "pneumococcal",
        "typhoidal", "tularemia", "pseudotubeculosis", "melioidosis",
        "bactereamia", "vaginosis", "lyme", "dacryocystitis", "actinomycetoma",
        "tuberculoma", "chlamydia", "scarlet", "tuberclosis", "pnuemonia",
        "menigitidis", "bacterimia", "leptospiroses", "brucellosi",
        "lemierres", "diptheria", "enterococcal", "endometritis", "septic",
        "borreliosis", "pneuomonia", "sepse", "ehrlichiosis",
        "staphyloenterotoxemia", "chorioamnionitis", "mastoiditis",
        "urosepsis", "sepsia", "meningoseptica", "septicemia", "keratolysis",
        "pyemia", "lepromatous", "tuberculous", "pyelonephritis",
        "polymicrobial disease"],
    "abbreviation":["TSS", "BV", "Carrion disease", "STEC", "Driveline",
        "ETEC", "UPEC", "Whipple", "SSTI", "LRI", "LRTI", "strep ", "MAC",
        "iNTS", "NSTI", "TB","CRBSI","STSS","VB", "IAI", "BSI", "RTI", "DGI",
        "CRE"],
    "also bacteria":["quintana"]
    },
"Disease maybe caused by pathogen":{
    "description":
        "Disease names that can be caused by a bacteria pathogen",
    "vocabulary":["gangrene","cholecystit", "tympanitis",
        "fibrinopurulent","pyoderma","pericoronitis","myalgia",
        "salpingitis", "mediastinitis","urethritis","duodenitis","mastitis",
        "vaginitis","cholangitis","ozena","mediastinitis","adenoiditis"
        "erythematous","orchiepididymitis","fasceitis","meningoencephalitis"
        "suppuration", "cholangitis","splenomegal","pyogeni","necrotising",
        "polyp", "hidradenitis", "scleritis", "gestroenteritis",
        "gastroenteritidis", "pharyngotonsillitis", "rhinosinusitis",
        "pleurisy", "urethitis", "gastritis", "pleuritis", "erythema", "pyuria", "pouchitis",
        "hematuresis", "ulcers", "diarheal", "myelitis", "decubitus", "melaena", "periodontits",
        "diarhea", "arteriopathy", "pleuricy", "osteitis", "gastroenteritis", "neumonia",
        "nephropathy", "hematuria", "diarrheal", "hydrocephaly", "uritritis", "endocarditits",
        "menigitis", "nosocomial", "diverticulitis", "tracheobronchitis", "malaise",
        "thrombocytopenic", "necrosis", "caries", "synusitis", "neonatorum", "epiglottitis",
        "uraemic", "vaginalis", "keratits", "vasculitis", "myelodysplasia", "endophtalmitis",
        "diarrhoeic", "adenomyosis", "trachiits", "pacreatitis", "bronchitis", "cholecystitis",
        "synovitis", "keratitis", "pemphigoid", "glomerulonephritis", "encephalitis",
        "diarrhoeal", "caseous", "debridement", "cystitis", "pancreatis", "keratohelcosis",
        "otitis", "scalded", "angiomatosis", "uretritis", "thrombocytopenia", "pneumonitis",
        "periimplantitis", "rhinorrhea", "diverticulits", "fasciitis", "rheumatic",
        "cheilitis", "diharrea", "pancreatitis", "gastrienteritis", "cystic", "angina",
        "ectopic", "thromboembolism", "sinusitis", "colitis", "dermatitis", "conjunctivitis",
        "purulent", "puerperal", "folliculitis", "endopthalmitis",
        "gasteroenteritis", "empyema", "gangrenous", "gastroentiritis", "pus",
        "eczema", "gastritits", "gastropathy", "ascitis", "cervicitis", "proctitis",
        "aortitis", "listeriosis", "oesophagitis", "laryngitis", "tenosynovitis",
        "periodontitis", "esophagitis", "laryngopharyngitis","cervictis",
        "pharyngitis", "endophthalmitis", "diarrhea", "diarreal", "pancolitis",
        "gastroenteretis","ileus", ],
    "abbreviation":["NEC","COPD", "NTM", "UTI", "FUI", "CRSSNP", "CAPD"]},
  "Unhealthy": {
    "description":
        "Vocabulary not found on healthy human hosts",
    "vocabulary":["expired", "pollut", "ischemia","haemorragic", "lymphadenoma", "ablation",
        "amputation", "rupture", "fibroma", "distension", "dysuria", "wound",
        "ruptured", "cavity", "ciliary", "papules","polytrauma","fever",
        "cholecystolithiasis", "disease", "spoil", "poison", "deseases",
        "dysbiosis","carrier", "carriage", "polyp", "hidradenitis",
        "acute", "ablation", "radiation", "immunosuppressed",
        "edematous", "obstructive", "silicosis",
        "eteroplasia", "atrophy", "occlusion", "rheumatoid",
        "haemolytic", "rupture",
        "lymphohistiocytosis",  "dysfunction", "ascites",
        "defect", "hepatitis", "adiposity", "coagulation",
        "replacement", "complicated", "dyskinesia",
        "hydrocele","tumors", "sclerosing", "hyperpyrexia", "disorder",
        "diabetes", "malformation", "aneurysm", "anemia",
        "hydatidiform", "choledocholith", "polycyst",
        "metaplasia", "anorexia", "cholecystectomy", "dyslipedemia",
        "pseudarthrosis", "klatskin",
        "atherosclerosis", "burnt", "proteus", "neoplasms", "hemorrhag",
        "oedema", "infertile", "polytrauma", "impotent", "abortion",
        "contracture", "enfermedad", "pouchitis", "ureteric", "ulcers",
        "concomitant", "contusion",  "hypovolemic",
        "melaena", "accident",
        "herniation", "lupus", "meningioma",  "choledochocyst", "arteriopathy",
        "nodularity", "incision", "pleuricy", "osteitis", "tetraplegia", "cancerous",
        "exertion", "carrier", "dysthyroid", "chock", "anaemia", "concussion", "confusion",
        "lesions", "laparatomy", "ischemic", "tympanitis", "thrombotic", "suppuration",
        "gastroenterit", "calculous", "hypercholesterolemia", "fibroids", "neumonia",
        "nephropathy", "hematuria", "prostatocystitis", "planus",
        "injury", "insufficiency", "obstruction", "hypokalemia",
        "rash", "fibrillation", "hydrocephaly", "reflux", "cholesteatoma", "seizure",
        "metastasis", "ulceroglandular", "urolithiasis", "appendicectomie",
        "thrombosis", "dizziness", "diabets", "ampulla", "idiopathic",
        "rickets", "uritritis", "burns", "otorrhea", "neuropathy", "endocarditits",
        "myoclonus", "rhinitis", "cardiopathy", "mainstem", "chiari", "ulcera", "laceration",
        "spondylolithesis", "congenital", "menigitis",
        "nephritis", "peritonitis", "fibroblastoma",
        "melitus", "cramps", "lesion", "perforans", "diverticulitis", "hyperplsia",
        "cyst", "diahrea", "tracheobronchitis", "embolism", "cysrtic", "hematologic",
        "renalinsufficiency", "fatigue", "infarction", "malaise", "thrombocytopenic",
        "vomiting", "arrhythmia", "asphyxia", "enterocolitis", "pemphigus", "luxation",
        "myeloblastic","immunocompromised","synusitis",
        "migraine", "hyperplasia", "gingivitis", "relapsing", "myelocytic",
        "feverish", "psoriasis", "illness", "arthiritis", "malformations",
        "neurosurgical", "cancer", "myositis", "erosive", "posioning", "emphysema",
        "enteritis", "uraemic", "appendectomy", "pyogenic", "keratits", "metastasized",
        "emptysis", "vasculitis", "asthmatic", "poisoned", "atypical", "palsy",
        "aplastic", "tumor", "burned", "swelling", "bronchopneumonia", "failure",
        "abnormalities", "encephalomyelitis",
        "acidosis", "retention", "chemotherapy", "melanoma", "ache", "myelodysplasia",
        "hodgkin", "pericoronitis", "subacute", "trauma", "crohn",
        "pneamonia", "headache", "adenomyosis", "trachitis", "ventriculostomy",
        "erythematosus", "trachiits", "illnes", "pacreatitis", "acyanotic",
        "diseased", "keratoacanthoma", "gastroenteritides", "sore", "diarrhear",
        "sick", "bronchitis", "shock", "erythematous", "hepatectomy",
        "pleumonia", "orchiepididymitis", "paraplegia", "fasceitis", "enteropathy",
        "difficulties", "chill", "synovitis", "hypertensive", "urethroplasty",
        "keratitis", "nephroctic", "dyspesia", "paralysis", "encephalopathy", "pemphigoid",
        "dermatomyositis", "remnant", "prostatitis",
        "hematencephalon", "glomerulonephritis", "burn", "encephalitis", "uropathy",
        "haemophagocytic", "basaliom", "bronchiolitis", "hyperglycemia",
        "adenocarcinoma", "leukemia", "carcinoma", "hemorroids",
        "lymphoblastic", "leukaemia", "metastases", "haemorrhage", "pain", "cystitis",
        "endocarditis", "fibosis", "arthralgia", "pancreatis", "discitis",
        "bronchospasm", "acuta", "keratohelcosis", "disorders", "osteosarcoma",
        "otitis", "injuries", "osteoarthritis",
        "grafting", "angiomatosis", "campylobacyteriosis", "asthma",
        "asthema", "hemopneumothorax", "febrile", "Epstein", "consciousness",
        "quadriplegia", "edema", "diesase", "acalculous", "deficiency",
        "uretritis", "ictus", "jaundice", "thrombocytopenia", "pneumonitis",
        "pneumonia", "arthralgias", "periimplantitis",
        "scar", "myeloma", "coeliac", "hyperbilirubinemia", "colectomy", "mellitus",
        "rhinorrhea", "stroke", "arthritis", "uremia", "ilness", "diverticulits",
        "herpeticum", "cirrhosis", "fasciitis", "fasciculation", "emergency",
        "bloody", "rheumatic", "penumonia",
        "crescentic", "hematemesis", "spastic", "shok", "dyspnea", "cavitary",
        "arthroplasty", "cheilitis", "hydronephrosis", "dyspepsias", "parotidectomy",
        "pancreatitis", "enterocutaneous", "emesis", "chronically", "gastrienteritis",
        "monocytic", "cystic", "nephrotic", "atresia", "angina", "fistula",
        "granuloma", "vomit", "encephalorrhagia", "ectopic", "infertility",
        "inflammatory", "photophobia", "thromboembolism", "ozena", "purpuric",
        "macroadenoma", "inflammation", "fibroid", "stricture", "diarrhoea",
        "stomachache", "bleed", "sinusitis", "colitis",
        "hyperphosphatemia", "gastroesophageal", "lyme", "dermatitis", "thrombembolia",
        "dacryocystitis", "conjunctivitis", "diabetec",
        "cholangiocarcinoma", "suffered", "pancytopenia",
        "megacolon", "tuberculoma", "diabetus", "ulcus", "atopic",
        "fiborsis", "acne", "varicose", "folliculitis", "hydrocephalus",
        "proteinuria", "congestion",
        "gasteroenteritis", "tumour", "distress", "malignant",
        "mediastinitis", "gastroentiritis", "ulcer", "diptheria", "squamous",
        "traumatic", "recurrent", "urethritis", "duodenitis", "eczema",
        "hemolysis", "gastritits","gastropathy", "dysouria", "diagnosed",
        "anemic", "scleroderma", "autohepatitis", "vesicoureteral", "ascitis",
        "neuroglioma", "cervicitis", "diarrhea",
        "graft", "prosthetic", "bleeding", "proctitis", "gist",
        "immunodeficiency","endometriosis", "gout", "haemorrhagic",
        "cardiogenic", "malnutrition", "diarhhea", "fribosis", "oesophagitis",
        "dyspepsia", "vopalitelnymi", "emboli", "meningiomas", "xerosis",
        "kyphoscolosis", "diarrhia", "neutropenia", "hernia", "hypohepatia",
        "malignancy", "haemorhagic", "cholecytitis", "therapy", "tenosynovitis",
        "bethesdensis", "periodontitis","esophagitis", "myelodysplastic", "anoxic",
        "bronchiectasis", "ulcerative", "neurosurgery", "tuberculous",
        "gravis", "deformity", "bursitis", "hepatosplenomegaly",
        "sicca", "compromised", "clinical"],
    "abbreviation":["AIDS", "CHF", "SCID", "BPCO", "HIV", "STD", "GERD", "UTI",
        "MVA", "NHL", "RF", "MAL", "MICU", "Guillain", "Lewy", "Barrett",
        "Barr", "CRF", "Crohns","AECOPD", "ESRD", "NUD","Hodgkins","FUO", "APR",
        "BAL", "IBS", "AML", "CF", "PICGN", "UCI", "RHD", "OSAS", "HCV",
        "CRSWNP", "DFU", "OSAS", "Pauci-immune", "MDR"]},
  "Non Pathogen": {
    "description":
        "Vocabulary found on non-pathogogenic bacteria",
    "vocabulary":["health", "attenuat",
        "volunteer", "gastroenterology", "dysbiosis", "probiotic", "commensal",
        "biome", "vaccine", "health", "noninfection", "donor", "reference"
        "gastroenterology", "beneficial", "non-patho", "no-patho"],
    "abbreviation":["Unified Human Gastrointestinal Genome","human vaccine",
        "Human Vaccine"]},
  "Flora Microbiome": {
    "description":
        "Vocabulary found on non-pathogogenic bacteria (related to microbiome)",
    "vocabulary":[
         "flora", "microbiom", "microbiot", "flora", "gut", "inhabit"],
    "abbreviation":["HMP", "UHGG", "HSKMP", "HOMD",
            "Human Microbiome Project", "Unified Human Gastrointestinal Genome",
            "Human Skin Microbiome Project", "Human Metagenome",
            "human oral microbiome database"]},
  "Probiotic": {
    "description":
        "Vocabulary found on non-pathogogenic bacteria (related to probiotics)",
    "vocabulary":["probiotic", "novel food", "feed additive", "food enzyme",
        "flavouring", "nutritional additive", "sensory additives"
        "fermentation", "cheese", "beer", "vinegar", "fermented", "wine",
        "bread", "yoghurt", "curd", "pickle", "sauerkraut", "chocolate",
        "coffee", "liquor", "soy sauce", "miso", "soy stinky tofu",
        "natto", "dairy product", "kefir", "cider", "alcohol", "kimchi", "butter",
        "buttermilk", "sour cream", "curd", "oncom", "kombucha",
        "tempeh", "yogurt"],
    "abbreviation":["tea", "Tea"]},
  "Extreme Conditions": {
    "description":
        "Vocabulary found on bacteria unable to live in humans",
    "vocabulary": ["hyperpiezophile", "hyperthermophile", "piezophile",
        "barophile", "psychrophile", "cryophile","sulphophile", "termophile"],
    "abbreviation":[]},}
